In [ ]:
import numpy as np

file_path = "/home/jacinto/robot-grasp/third_party/video_to_taxposed/SpaTracker/assets/sintel_bandage/00001.npy"
data = np.load(file_path, allow_pickle=True)

print(data)
for key in data.files:
    print(f"{key}: {data[key]}")

['shapenet_id', 'ee_pose_world', 'robot_joints', 'obj_pose_world', 'obj_pose_camera', 'object_pointcloud', 'depth', 'seg', 'camera_poses', 'obj_model_file', 'obj_model_file_dec', 'gripper_pts', 'gripper_pts_gaussian', 'gripper_pts_uniform', 'gripper_contact_pose', 'table_urdf']
shapenet_id: 5c48d471200d2bf16e8a121e6886e18d
ee_pose_world: [ 0.42159536  0.09980665  1.12025392  0.99927962 -0.03309502  0.00490998
 -0.01791276]
robot_joints: [-0.09536123  0.06952111  0.31750048 -2.6356873   0.02570423  2.72014368
  1.04947529]
obj_pose_world: [0.42577127 0.17105306 1.0453528  0.70696861 0.01397786 0.01397786
 0.70696861]
obj_pose_camera: [-0.14981085 -0.00145031  1.02182291  0.93785063 -0.06014036  0.27127562
 -0.20791552]
object_pointcloud: [[0.41002861 0.27955605 1.13718287]
 [0.41280154 0.28000885 1.13734466]
 [0.36445616 0.22364919 1.14583789]
 ...
 [0.37795358 0.09329653 0.96664942]
 [0.38069106 0.09408818 0.96538625]
 [0.38318119 0.09416615 0.96457915]]
depth: [array([1.1381854, 1.137